### ISSUE TITLE
Error while installing wrv package

### ISSUE THREAD

**Issue by ysubash** [USGS-R/wrv#2]
I am getting below error while installing "wrv" package in R/RStudio 

```
> repos <- c("http://owi.usgs.gov/R", getOption("repos"))
> install.packages("wrv", repos = repos, dependencies = TRUE)
```

Warning in install.packages :
  package ‘wrv’ is not available (for R version 3.2.5)
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository http://owi.usgs.gov/R/src/contrib:
  cannot open URL 'http://owi.usgs.gov/R/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘wrv’ is not available (for R version 3.2.5)

```
sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: i686-pc-linux-gnu (32-bit)
Running under: Ubuntu precise (12.04.5 LTS)
```

**Comment by ysubash** [comment]
Updated Rstudio to Version 1.0.44 and now the packages installation process starts with compiling the fortran codes and then halts with the below error 

**moving datasets to lazyload DB
Error : cannot allocate buffer
ERROR: lazydata failed for package ‘wrv’**

**Comment by jfisher-usgs** [comment]
Check out the latest version of wrv and let me know if you're still having problems.
