### ISSUE TITLE
No model.rda file in https://water.usgs.gov/GIS/dsdl/gwmodels/SIR2016-5080/model.zip

### ISSUE THREAD

**Issue by julianaspector** [USGS-R/wrv#24]
I'm trying to load R objects from model.rda. However, there doesn't appear to be a model.rda file in https://water.usgs.gov/GIS/dsdl/gwmodels/SIR2016-5080/model.zip after downloading file, unzipping, and copying contents to archive folder in working directory.

**Comment by jfisher-usgs** [comment]
Should have included this file in the model archive, even though its not necessary for running the calibrated model. One suggestion is to grab it from [here](https://github.com/jfisher-usgs/wrv-training/tree/master/archive). Also, keep in mind that processing instructions exist for a [wrv-training](https://jfisher-usgs.github.io/wrv-training/index.html)  course I gave a few years back.
